Added Contact Form
Addisu87/Addisu87.github.io pull request #2
Opened 2022-04-26 22:19 UTC by Addisu87

I have added the contact form with built-in validation.

2022-04-26 22:39 UTC, koomekevo requested changes
Hi @Addisu87 , 

<img src="https://media2.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 22:39 UTC, koomekevo commented on index.html
> +						<form action="#" method="post" id="form">
@Addisu87 Kindly use [formspree](https://formspree.io/html) service for form `action` and  `method` attribute.

2022-04-27 06:49 UTC, danmainah approved these changes
Hi @Addisu87 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights

✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 06:49 UTC, danmainah commented on index.html
> +								</div>
- [ ] [[OPTIONAL] Kindly add the `maxlength="30"` attribute, this will enable you restrict the number of characters the Name input can take

2022-04-27 07:37 UTC, merged