Added sections
Addisu87/Addisu87.github.io pull request #4
Opened 2022-04-28 22:22 UTC by Addisu87

2022-04-29 20:45 UTC, Munsa1 requested changes
Hi @Addisu87 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no pull request description
![image](https://user-images.githubusercontent.com/81932478/166066820-ba54bc60-f427-4fbb-9878-0f93edeca84d.png)

Kindly add a description and someone will review your work.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-29 22:18 UTC, Addisu87 commented
Changing different png into SVG file and styling as the Figma design.

2022-04-29 22:27 UTC, youmari requested changes
#
Hi @Addisu87 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] Doesn't have a Descriptive short summary 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-29 22:33 UTC, Addisu87 commented
@[youmari](https://github.com/youmari) where can I add this short summary.

2022-04-29 23:43 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Please make sure you are using GitFlow. Currently, you are using github flow. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-29 23:43 UTC, arslanbisharat commented on style.css
> +  /* navbar */
- [ ] Use media queries for the Desktop breakpoint in the CSS file. (the value for `min-width` property should be in range of `768px` or wider)

2022-04-30 01:48 UTC, youmari commented
> @[youmari](https://github.com/youmari) where can I add this short summary.

you can add it at the top of the page  click on the three-dot then edit to add it
![image](https://user-images.githubusercontent.com/61790587/166085872-9ac1e471-36b0-48ed-92ca-401fa66dd9aa.png)

2022-04-30 13:04 UTC, Addisu87 commented
@[youmari](https://github.com/youmari) I have managed to add GitFlow but the branches are diverted. I think the first one is in GitHub flow and the other is using GitFlow. Shall I create another PR or simply request to use the new one. If you have any suggestions please send me.

2022-04-30 14:39 UTC, RolandM99 approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @Addisu87 , 

### Now your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Now you can take a rest a prepare your next week!
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 14:46 UTC, merged