Accessibility features
Addisu87/Addisu87.github.io pull request #6
Opened 2022-05-03 21:09 UTC by Addisu87

We are working as a team and incorporate the following points as a summary.
     -Title improved
     -Red borders are included when forms are not properly filled (invalid)
     -Audio control is included in the first card for text to speech
     -Resize pictures in the work section for hover
     -button color "let's connect" corrected
    -navigate links configured to move inside the page
    -All the headings were checked, no changes were needed
    -Contrast color checked, no changes needed

2022-05-03 21:50 UTC, ShahierNashaat requested changes
Hi @Addisu87 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 21:50 UTC, ShahierNashaat commented on index.html
>                Experimental content creation feature that allows users to add to
- [ ] Please make your webpage resizeable.
![Screenshot from 2022-05-03 23-43-18](https://user-images.githubusercontent.com/33752735/166571670-853a3254-9e27-41b7-9dbc-8bf3bddeff2f.png)

2022-05-03 21:50 UTC, ShahierNashaat commented on index.html
> +              <h4 class="heading-connect">LET'S CONNECT</h4></a
- [ ] Please change the `h4` tag to `h2` tag as the Heading levels should have a meaningful hierarchy, or you can change it to any other tag but not the heading tags.

2022-05-04 08:06 UTC, m05e5 approved these changes
# Hi @andym80 , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete! 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 12:46 UTC, merged